//Do not modify this file, it will be autogenerated
import DropMenuDecorator  from './DropMenuDecorator';
import DynamicForm  from './DynamicForm';
import DynamicQueryForm  from './DynamicQueryForm';
import EditField  from './EditField';
import MenuDecorator  from './MenuDecorator';
import Moment  from './Moment';
import PermissionRouterLink  from './PermissionRouterLink';
import SelectHours  from './SelectHours';
import SelectJobTitle  from './SelectJobTitle';
import SelectTabs  from './SelectTabs';
import SelectTimeout  from './SelectTimeout';
import TimeZoneSelect  from './TimeZoneSelect';

const commonComponents = {
    DropMenuDecorator : {
       install : (Vue) =>{
           Vue.component('DropMenuDecorator',DropMenuDecorator );
       }
    },
    DynamicForm : {
       install : (Vue) =>{
           Vue.component('DynamicForm',DynamicForm );
       }
    },
    DynamicQueryForm : {
       install : (Vue) =>{
           Vue.component('DynamicQueryForm',DynamicQueryForm );
       }
    },
    EditField : {
       install : (Vue) =>{
           Vue.component('EditField',EditField );
       }
    },
    MenuDecorator : {
       install : (Vue) =>{
           Vue.component('MenuDecorator',MenuDecorator );
       }
    },
    Moment : {
       install : (Vue) =>{
           Vue.component('Moment',Moment );
       }
    },
    PermissionRouterLink : {
       install : (Vue) =>{
           Vue.component('PermissionRouterLink',PermissionRouterLink );
       }
    },
    SelectHours : {
       install : (Vue) =>{
           Vue.component('SelectHours',SelectHours );
       }
    },
    SelectJobTitle : {
       install : (Vue) =>{
           Vue.component('SelectJobTitle',SelectJobTitle );
       }
    },
    SelectTabs : {
       install : (Vue) =>{
           Vue.component('SelectTabs',SelectTabs );
       }
    },
    SelectTimeout : {
       install : (Vue) =>{
           Vue.component('SelectTimeout',SelectTimeout );
       }
    },
    TimeZoneSelect : {
       install : (Vue) =>{
           Vue.component('TimeZoneSelect',TimeZoneSelect );
       }
    },
}
export default commonComponents;