<template>
    <div>
            <Option value="Pacific/Midway">(UTC-11:00) International Date Line West, Midway Island</Option>
            <Option value="Pacific/Pago_Pago">(UTC-11:00) American Samoa</Option>
            <Option value="Pacific/Honolulu">(UTC-10:00) Hawaii</Option>
            <Option value="America/Juneau">(UTC-08:00) Alaska</Option>
            <Option value="America/Los_Angeles" label="(UTC-07:00) Pacific Time (US & Canada)">(UTC-07:00) Pacific Time (US & Canada)</Option>
            <Option value="America/Tijuana">(UTC-07:00) Tijuana</Option>
            <Option value="America/Denver" label="(UTC-06:00) Mountain Time (US & Canada)">(UTC-06:00) Mountain Time (US & Canada)</Option>
            <Option value="America/Phoenix">(UTC-07:00) Arizona</Option>
            <Option value="America/Chihuahua">(UTC-06:00) Chihuahua</Option>
            <Option value="America/Mazatlan">(UTC-06:00) Mazatlan</Option>
            <Option value="America/Chicago">(UTC-05:00) Central Time (US & Canada)</Option>
            <Option value="America/Regina">(UTC-06:00) Saskatchewan</Option>
            <Option value="America/Mexico_City">(UTC-05:00) Guadalajara, Mexico City</Option>
            <Option value="America/Monterrey">(UTC-05:00) Monterrey</Option>
            <Option value="America/Guatemala">(UTC-06:00) Central America</Option>
            <Option value="America/New_York">(UTC-04:00) Eastern Time (US & Canada)</Option>
            <Option value="America/Indiana/Indianapolis">(UTC-04:00) Indiana (East)</Option>
            <Option value="America/Bogota">(UTC-05:00) Bogota</Option>
            <Option value="America/Lima">(UTC-05:00) Lima, Quito</Option>
            <Option value="America/Halifax">(UTC-03:00) Atlantic Time (Canada)</Option>
            <Option value="America/Caracas">(UTC-04:00) Caracas</Option>
            <Option value="America/La_Paz">(UTC-04:00) La Paz</Option>
            <Option value="America/Santiago">(UTC-03:00) Santiago</Option>
            <Option value="America/St_Johns">(UTC-02:30) Newfoundland</Option>
            <Option value="America/Sao_Paulo">(UTC-03:00) Brasilia</Option>
            <Option value="America/Argentina/Buenos_Aires">(UTC-03:00) Buenos Aires</Option>
            <Option value="America/Guyana">(UTC-04:00) Georgetown</Option>
            <Option value="America/Godthab">(UTC-02:00) Greenland</Option>
            <Option value="Atlantic/South_Georgia">(UTC-02:00) Mid-Atlantic</Option>
            <Option value="Atlantic/Azores">(UTC+00:00) Azores</Option>
            <Option value="Atlantic/Cape_Verde">(UTC-01:00) Cape Verde Is.</Option>
            <Option value="Europe/Dublin">(UTC+01:00) Dublin</Option>
            <Option value="Europe/London">(UTC+01:00) Edinburgh, London</Option>
            <Option value="Europe/Lisbon">(UTC+01:00) Lisbon</Option>
            <Option value="Africa/Casablanca">(UTC+01:00) Casablanca</Option>
            <Option value="Africa/Monrovia">(UTC+00:00) Monrovia</Option>
            <Option value="Etc/UTC">(UTC+00:00) UTC</Option>
            <Option value="Europe/Belgrade">(UTC+02:00) Belgrade</Option>
            <Option value="Europe/Bratislava">(UTC+02:00) Bratislava</Option>
            <Option value="Europe/Budapest">(UTC+02:00) Budapest</Option>
            <Option value="Europe/Ljubljana">(UTC+02:00) Ljubljana</Option>
            <Option value="Europe/Prague">(UTC+02:00) Prague</Option>
            <Option value="Europe/Sarajevo">(UTC+02:00) Sarajevo</Option>
            <Option value="Europe/Skopje">(UTC+02:00) Skopje</Option>
            <Option value="Europe/Warsaw">(UTC+02:00) Warsaw</Option>
            <Option value="Europe/Zagreb">(UTC+02:00) Zagreb</Option>
            <Option value="Europe/Brussels">(UTC+02:00) Brussels</Option>
            <Option value="Europe/Copenhagen">(UTC+02:00) Copenhagen</Option>
            <Option value="Europe/Madrid">(UTC+02:00) Madrid</Option>
            <Option value="Europe/Paris">(UTC+02:00) Paris</Option>
            <Option value="Europe/Amsterdam">(UTC+02:00) Amsterdam</Option>
            <Option value="Europe/Berlin">(UTC+02:00) Berlin, Bern</Option>
            <Option value="Europe/Rome">(UTC+02:00) Rome</Option>
            <Option value="Europe/Stockholm">(UTC+02:00) Stockholm</Option>
            <Option value="Europe/Vienna">(UTC+02:00) Vienna</Option>
            <Option value="Africa/Algiers">(UTC+01:00) West Central Africa</Option>
            <Option value="Europe/Bucharest">(UTC+03:00) Bucharest</Option>
            <Option value="Africa/Cairo">(UTC+02:00) Cairo</Option>
            <Option value="Europe/Helsinki">(UTC+03:00) Helsinki</Option>
            <Option value="Europe/Kiev">(UTC+03:00) Kyiv</Option>
            <Option value="Europe/Riga">(UTC+03:00) Riga</Option>
            <Option value="Europe/Sofia">(UTC+03:00) Sofia</Option>
            <Option value="Europe/Tallinn">(UTC+03:00) Tallinn</Option>
            <Option value="Europe/Vilnius">(UTC+03:00) Vilnius</Option>
            <Option value="Europe/Athens">(UTC+03:00) Athens</Option>
            <Option value="Europe/Istanbul">(UTC+03:00) Istanbul</Option>
            <Option value="Europe/Minsk">(UTC+03:00) Minsk</Option>
            <Option value="Asia/Jerusalem">(UTC+03:00) Jerusalem</Option>
            <Option value="Africa/Harare">(UTC+02:00) Harare</Option>
            <Option value="Africa/Johannesburg">(UTC+02:00) Pretoria</Option>
            <Option value="Europe/Moscow">(UTC+03:00) Moscow, St. Petersburg, Volgograd</Option>
            <Option value="Asia/Kuwait">(UTC+03:00) Kuwait</Option>
            <Option value="Asia/Riyadh">(UTC+03:00) Riyadh</Option>
            <Option value="Africa/Nairobi">(UTC+03:00) Nairobi</Option>
            <Option value="Asia/Baghdad">(UTC+03:00) Baghdad</Option>
            <Option value="Asia/Tehran">(UTC+04:30) Tehran</Option>
            <Option value="Asia/Muscat">(UTC+04:00) Abu Dhabi, Muscat</Option>
            <Option value="Asia/Baku">(UTC+04:00) Baku</Option>
            <Option value="Asia/Tbilisi">(UTC+04:00) Tbilisi</Option>
            <Option value="Asia/Yerevan">(UTC+04:00) Yerevan</Option>
            <Option value="Asia/Kabul">(UTC+04:30) Kabul</Option>
            <Option value="Asia/Yekaterinburg">(UTC+05:00) Ekaterinburg</Option>
            <Option value="Asia/Karachi">(UTC+05:00) Islamabad, Karachi</Option>
            <Option value="Asia/Tashkent">(UTC+05:00) Tashkent</Option>
            <Option value="Asia/Kolkata">(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi</Option>
            <Option value="Asia/Kathmandu">(UTC+05:45) Kathmandu</Option>
            <Option value="Asia/Dhaka">(UTC+06:00) Astana, Dhaka</Option>
            <Option value="Asia/Colombo">(UTC+05:30) Sri Jayawardenepura</Option>
            <Option value="Asia/Almaty">(UTC+06:00) Almaty</Option>
            <Option value="Asia/Novosibirsk">(UTC+07:00) Novosibirsk</Option>
            <Option value="Asia/Rangoon">(UTC+06:30) Rangoon</Option>
            <Option value="Asia/Bangkok">(UTC+07:00) Bangkok, Hanoi</Option>
            <Option value="Asia/Jakarta">(UTC+07:00) Jakarta</Option>
            <Option value="Asia/Krasnoyarsk">(UTC+07:00) Krasnoyarsk</Option>
            <Option value="Asia/Shanghai">(UTC+08:00) Beijing</Option>
            <Option value="Asia/Chongqing">(UTC+08:00) Chongqing</Option>
            <Option value="Asia/Hong_Kong">(UTC+08:00) Hong Kong</Option>
            <Option value="Asia/Urumqi">(UTC+06:00) Urumqi</Option>
            <Option value="Asia/Kuala_Lumpur">(UTC+08:00) Kuala Lumpur</Option>
            <Option value="Asia/Singapore">(UTC+08:00) Singapore</Option>
            <Option value="Asia/Taipei">(UTC+08:00) Taipei</Option>
            <Option value="Australia/Perth">(UTC+08:00) Perth</Option>
            <Option value="Asia/Irkutsk">(UTC+08:00) Irkutsk</Option>
            <Option value="Asia/Ulaanbaatar">(UTC+09:00) Ulaan Bataar</Option>
            <Option value="Asia/Seoul">(UTC+09:00) Seoul</Option>
            <Option value="Asia/Tokyo">(UTC+09:00) Osaka, Sapporo, Tokyo</Option>
            <Option value="Asia/Yakutsk">(UTC+09:00) Yakutsk</Option>
            <Option value="Australia/Darwin">(UTC+09:30) Darwin</Option>
            <Option value="Australia/Adelaide">(UTC+09:30) Adelaide</Option>
            <Option value="Australia/Melbourne">(UTC+10:00) Canberra, Melbourne</Option>
            <Option value="Australia/Sydney">(UTC+10:00) Sydney</Option>
            <Option value="Australia/Brisbane">(UTC+10:00) Brisbane</Option>
            <Option value="Australia/Hobart">(UTC+10:00) Hobart</Option>
            <Option value="Asia/Vladivostok">(UTC+10:00) Vladivostok</Option>
            <Option value="Pacific/Guam">(UTC+10:00) Guam</Option>
            <Option value="Pacific/Port_Moresby">(UTC+10:00) Port Moresby</Option>
            <Option value="Asia/Magadan">(UTC+11:00) Magadan, Solomon Is.</Option>
            <Option value="Pacific/Noumea">(UTC+11:00) New Caledonia</Option>
            <Option value="Pacific/Fiji">(UTC+12:00) Fiji</Option>
            <Option value="Asia/Kamchatka">(UTC+12:00) Kamchatka</Option>
            <Option value="Pacific/Majuro">(UTC+12:00) Marshall Is.</Option>
            <Option value="Pacific/Auckland">(UTC+12:00) Auckland, Wellington</Option>
            <Option value="Pacific/Tongatapu">(UTC+13:00) Nuku'alofa</Option>
            <Option value="Pacific/Fakaofo">(UTC+13:00) Tokelau Is.</Option>
            <Option value="Pacific/Apia">(UTC+13:00) Samoa</Option>
            <Option value="America/Cuiaba">(UTC-04:00) Cuiaba</Option>
    </div>
</template>
<script>
    export default{
        name: 'TimeZoneSelect',
    }
</script>