/**
 * Created by binwang on 17/11/8.
 */
export default [
    // 'user.add',
    // 'user.del',
    // 'user.user_setting',
    // 'user.show_permission',
    // 'user.edit',
    // 'user.reset_pwd',
    // 'escalationPolicy.new',
    // 'escalationPolicy.read',
    // 'escalationPolicy.edit',
    // 'escalationPolicy.delete',
    // 'schedule.read',
    // 'schedule.new',
    // 'schedule.copy',
    // 'schedule.delete',
    // 'schedule.edit',
    // 'schedule.override',
    // 'schedule.revert',
    // 'schedule.upcoming_override',
    // 'schedule.delete_override',
    // 'service.read',
    // 'service.new',
    // 'service.dis_or_en_able',
    // 'service.delete',
    // 'service.new_incident',
    // 'service.new_integration',
    // 'service.edit_integration',
    // 'service.move_integration',
    // 'service.delete_integration',
    'service.new_extension',
    'service.edit_extension',
    'service.delete_extension',
    // 'service.new_eventRule',
    // 'service.edit_eventRule',
    // 'service.delete_eventRule',
    // 'service.move_eventRule',
    // 'service.read_maintenance',
    // 'service.new_maintenance',
    // 'service.edit_maintenance',
    // 'service.end_maintenance',
    // 'service.delete_maintenance',
    // 'incident.read',
    // 'incident.acknowledge',
    // 'incident.reassign',
    // 'incident.resolve',
    // 'incident.snooze',
    // 'incident.merge',
    //'incident.new',
    // 'incident.add_responder',
    // 'incident.add_note',
    // 'incident.manager_subscriber',
    // 'incident.redact',
]